### PR TITLE
WIP: reboot for maximum community compatibility

### PR DESCRIPTION
**Pull request by alexandru**
Changes:

1. `funfix-types` gets a reboot, to be based on the [static-land](https://github.com/rpominov/static-land) specification and to be a top project - its purpose is to expose only types, with no code or other dependencies
2. the higher-kinded encoding is now compatible with that of [fp-ts](https://github.com/gcanti/fp-ts), also see this issue: https://github.com/gcanti/fp-ts/issues/252
3. `funfix–core`, `funfix-exec` and `funfix-effect` now all depend on and implement `funfix-types` (versus the other way around, as is currently)
4. new `funfix-laws` project, because JavaScript binary size counts and exposing those laws in `funfix-types` just adds unnecessary weight
5. all data types in `funfix-core`, `funfix-exec` and `funfix-effect` also expose [Fantasy-Land](https://github.com/fantasyland/fantasy-land) methods

Other breaking changes:

1. `recover` and `recoverWith` (e.g. `Try`, `Future` and `IO`)  get renamed to `onErrorRecover` and `onErrorRecoverWith`, because it's more IDE friendly and we want to expose *more* error handling utilities

Work in progress.

### CODE REVIEW

**Comment by gcanti** [comment]
@alexandru about the HKT encoding, what you think about this change? https://github.com/gcanti/fp-ts/issues/290#issuecomment-359801053

TypeScript 2.7.x (under `strict: true`) now complains if you don't initialize all fields. 
In order to workaround these stricter class property checks, you can either mark those fields with `!` (a syntax that AFAIK is not backward compatible with ts 2.6.2) or write them as literals (which are removed by prettier).

Reference: https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/

**Comment by alexandru** [comment]
@gcanti shit, so TypeScript broke my code on every `2.x` release 😨 haven't upgraded to 2.7 yet because it breaks the latest Lodash typings as well, which is apparently needed for `babel-core`.

Anyway, if that fixes the problem, then it's all good. I'm a little upset that I'll still have to use underscore (`_A`) in Flow, due to Flow not supporting literal properties, but I guess a different encoding is inevitable.

My worry is that this is a temporary workaround and I hope they won't change the rules again in TS 2.8 — guess we can always do an `= undefined as any`, which would have runtime effects.

**Comment by gcanti** [comment]
> so TypeScript broke my code on every 2.x release

Not sure about that, users shouldn't get errors since they are just consuming the definition files, right?

> but I guess a different encoding is inevitable

oh about that... it turns out Flow actually supports HKTs, take a look at this encoding https://github.com/gcanti/fp-ts/blob/25f1b74585b3309a68bb591cfaf3b8c325215aee/src/HKT.js.flow#L11

**Comment by alexandru** [comment]
> Not sure about that, users shouldn't get errors since they are just consuming the definition files, right?

Sure, but it breaks binary compatibility, especially in cases where the library is used as a transitive dependency. So if some library ended up depending on the old encoding in order to integrate with funfix or fp-ts, then our new versions change the encoding, that's breakage which gets to be visible at the user's callsite.

Very similar actually to me upgrading TS 2.7 only to discover that Lodash, used as a transitive dependency, is breaking my build and with me unable to fix it because I don't control Lodash (although in this case I could make the compiler to be less strict).

Anyway, that's just a minor rant, I agree with the change.

> oh about that... it turns out Flow actually supports HKTs, take a look at this encoding https://github.com/gcanti/fp-ts/blob/25f1b74585b3309a68bb591cfaf3b8c325215aee/src/HKT.js.flow#L11

Thanks for that, I don't know how it works yet, but will investigate 👏

**Comment by alexandru** [comment]
M'kay, I moved my rant to TypeScript's repo — https://github.com/Microsoft/TypeScript/issues/21625

😀

**Comment by gcanti** [comment]
@alexandru UPDATE: https://github.com/gcanti/fp-ts/issues/290#issuecomment-363679621
It doesn't worth a breaking change without further garanties, I'm going to keep the current encoding with underscores (sorry for the confusion)

**Comment by alexandru** [comment]
@gcanti thanks for the update and no worries, I was thinking of the same thing — eventually everybody will be on a version > 2.7 and then we can use the `definite assignment assertion` syntax. On the other hand we have no guarantee that this proposed change will continue to work.

**Comment by alexandru** [comment]
Moving over to PR #101

**Pull request closed without merging**
